import json
from pathlib import Path, PurePosixPath
from typing import Any

from local_assistant.models.command_proposal import CommandProposal
from local_assistant.models.orchestrator_result import OrchestratorResult
from local_assistant.orchestrator.orchestrator import Orchestrator


class ExecuteCommandProposal:
    """
    Action that executes a validated command proposal.

    This action does not call an LLM.

    It receives a structured CommandProposal, validates it locally,
    enforces confirmation for write operations, and then delegates execution
    to the orchestrator.
    """

    ALLOWED_OPERATIONS: dict[str, dict[str, set[str]]] = {
        "read_note": {
            "required": {"relative_path"},
            "optional": set(),
        },
        "search_notes": {
            "required": {"query"},
            "optional": set(),
        },
        "append_note": {
            "required": {"relative_path", "content"},
            "optional": set(),
        },
        "write_note": {
            "required": {"relative_path", "content"},
            "optional": {"overwrite"},
        },
    }

    WRITE_OPERATIONS = {
        "append_note",
        "write_note",
    }

    def __init__(self, orchestrator: Orchestrator) -> None:
        self.orchestrator = orchestrator

    def execute(
        self,
        proposal: CommandProposal,
        confirm: bool = False,
    ) -> OrchestratorResult:
        validation_error = self._validate_proposal(proposal)

        if validation_error is not None:
            return OrchestratorResult(
                success=False,
                message="Command proposal failed execution validation.",
                domain=proposal.domain,
                operation=proposal.operation,
                error=validation_error,
                data={
                    "arguments": proposal.arguments,
                },
            )

        if proposal.operation in self.WRITE_OPERATIONS and not confirm:
            return OrchestratorResult(
                success=False,
                message="Confirmation is required before executing this proposal.",
                domain=proposal.domain,
                operation=proposal.operation,
                error="CONFIRMATION_REQUIRED",
                data={
                    "arguments": proposal.arguments,
                },
            )

        return self.orchestrator.execute(
            domain=proposal.domain,
            operation=proposal.operation,
            **proposal.arguments,
        )

    def execute_from_file(
        self,
        proposal_file: str | Path,
        confirm: bool = False,
    ) -> OrchestratorResult:
        path = Path(proposal_file).expanduser()

        try:
            raw_content = path.read_text(encoding="utf-8")
        except OSError as exc:
            return OrchestratorResult(
                success=False,
                message="Failed to read proposal file.",
                domain="proposal",
                operation="execute_proposal",
                error="PROPOSAL_FILE_READ_ERROR",
                data={
                    "path": str(path),
                    "details": str(exc),
                },
            )

        try:
            payload = json.loads(raw_content)
        except json.JSONDecodeError as exc:
            return OrchestratorResult(
                success=False,
                message="Proposal file does not contain valid JSON.",
                domain="proposal",
                operation="execute_proposal",
                error="INVALID_PROPOSAL_JSON",
                data={
                    "path": str(path),
                    "details": str(exc),
                },
            )

        proposal = self._proposal_from_payload(payload)

        return self.execute(
            proposal=proposal,
            confirm=confirm,
        )

    def _proposal_from_payload(self, payload: dict[str, Any]) -> CommandProposal:
        """
        Accept either:

        1. a raw proposal object:
           {
             "domain": "...",
             "operation": "...",
             "arguments": ...
           }

        2. a CommandProposalResult JSON generated by:
           local-assistant --json propose "..."
           {
             "success": true,
             "proposal": {
               "domain": "...",
               "operation": "...",
               "arguments": ...
             }
           }
        """

        if "proposal" in payload and isinstance(payload["proposal"], dict):
            payload = payload["proposal"]

        domain = payload.get("domain", "")
        operation = payload.get("operation", "")
        arguments = payload.get("arguments", {})
        explanation = payload.get("explanation", "")
        requires_confirmation = payload.get("requires_confirmation", True)

        if not isinstance(arguments, dict):
            arguments = {}

        if not isinstance(requires_confirmation, bool):
            requires_confirmation = True

        return CommandProposal(
            domain=str(domain).strip().lower(),
            operation=str(operation).strip(),
            arguments=arguments,
            explanation=str(explanation).strip(),
            requires_confirmation=requires_confirmation,
        )

    def _validate_proposal(self, proposal: CommandProposal) -> str | None:
        if proposal.domain != "vault":
            return "UNSUPPORTED_DOMAIN"

        if proposal.operation not in self.ALLOWED_OPERATIONS:
            return "UNSUPPORTED_OPERATION"

        operation_spec = self.ALLOWED_OPERATIONS[proposal.operation]
        required_args = operation_spec["required"]
        optional_args = operation_spec["optional"]
        allowed_args = required_args | optional_args

        received_args = set(proposal.arguments.keys())

        missing_args = required_args - received_args
        if missing_args:
            return "MISSING_REQUIRED_ARGUMENT"

        unknown_args = received_args - allowed_args
        if unknown_args:
            return "UNKNOWN_ARGUMENT"

        for arg_name in required_args:
            value = proposal.arguments.get(arg_name)

            if not isinstance(value, str):
                return "INVALID_ARGUMENT_TYPE"

            if not value.strip():
                return "EMPTY_ARGUMENT"

        if "relative_path" in proposal.arguments:
            relative_path = proposal.arguments["relative_path"]

            if not self._is_safe_relative_path(relative_path):
                return "UNSAFE_RELATIVE_PATH"

        if "overwrite" in proposal.arguments:
            overwrite = proposal.arguments["overwrite"]

            if not isinstance(overwrite, bool):
                return "INVALID_OVERWRITE_ARGUMENT"

        return None

    def _is_safe_relative_path(self, relative_path: str) -> bool:
        path = PurePosixPath(relative_path)

        if path.is_absolute():
            return False

        if ".." in path.parts:
            return False

        return True
