import json
from pathlib import Path
from typing import Any

from local_assistant.models.command_proposal import CommandProposal
from local_assistant.models.orchestrator_result import OrchestratorResult
from local_assistant.orchestrator.orchestrator import Orchestrator
from local_assistant.validation.command_proposal_validator import (
    CommandProposalValidator,
)


class ExecuteCommandProposal:
    """
    Action that executes a validated command proposal.

    This action does not call an LLM.

    It receives a structured CommandProposal, validates it locally,
    enforces confirmation for write operations, and then delegates execution
    to the orchestrator.
    """

    def __init__(
        self,
        orchestrator: Orchestrator,
        validator: CommandProposalValidator | None = None,
    ) -> None:
        self.orchestrator = orchestrator
        self.validator = validator or CommandProposalValidator()

    def execute(
        self,
        proposal: CommandProposal,
        confirm: bool = False,
    ) -> OrchestratorResult:
        validation_error = self.validator.validate(proposal)

        if validation_error is not None:
            return OrchestratorResult(
                success=False,
                message="Command proposal failed execution validation.",
                domain=proposal.domain,
                operation=proposal.operation,
                error=validation_error,
                data={
                    "arguments": proposal.arguments,
                },
            )

        if self.validator.requires_confirmation(proposal) and not confirm:
            return OrchestratorResult(
                success=False,
                message="Confirmation is required before executing this proposal.",
                domain=proposal.domain,
                operation=proposal.operation,
                error="CONFIRMATION_REQUIRED",
                data={
                    "arguments": proposal.arguments,
                },
            )

        return self.orchestrator.execute(
            domain=proposal.domain,
            operation=proposal.operation,
            **proposal.arguments,
        )

    def execute_from_file(
        self,
        proposal_file: str | Path,
        confirm: bool = False,
    ) -> OrchestratorResult:
        path = Path(proposal_file).expanduser()

        try:
            raw_content = path.read_text(encoding="utf-8")
        except OSError as exc:
            return OrchestratorResult(
                success=False,
                message="Failed to read proposal file.",
                domain="proposal",
                operation="execute_proposal",
                error="PROPOSAL_FILE_READ_ERROR",
                data={
                    "path": str(path),
                    "details": str(exc),
                },
            )

        try:
            payload = json.loads(raw_content)
        except json.JSONDecodeError as exc:
            return OrchestratorResult(
                success=False,
                message="Proposal file does not contain valid JSON.",
                domain="proposal",
                operation="execute_proposal",
                error="INVALID_PROPOSAL_JSON",
                data={
                    "path": str(path),
                    "details": str(exc),
                },
            )

        if not isinstance(payload, dict):
            return OrchestratorResult(
                success=False,
                message="Proposal file JSON must be an object.",
                domain="proposal",
                operation="execute_proposal",
                error="INVALID_PROPOSAL_JSON",
                data={
                    "path": str(path),
                },
            )

        proposal = self._proposal_from_payload(payload)

        return self.execute(
            proposal=proposal,
            confirm=confirm,
        )

    def _proposal_from_payload(self, payload: dict[str, Any]) -> CommandProposal:
        """
        Accept either:

        1. a raw proposal object:
           {
             "domain": "...",
             "operation": "...",
             "arguments": ...
           }

        2. a CommandProposalResult JSON generated by:
           local-assistant --json propose "..."
           {
             "success": true,
             "proposal": {
               "domain": "...",
               "operation": "...",
               "arguments": ...
             }
           }
        """

        if "proposal" in payload and isinstance(payload["proposal"], dict):
            payload = payload["proposal"]

        domain = payload.get("domain", "")
        operation = payload.get("operation", "")
        arguments = payload.get("arguments", {})
        explanation = payload.get("explanation", "")
        requires_confirmation = payload.get("requires_confirmation", True)

        if not isinstance(arguments, dict):
            arguments = {}

        if not isinstance(requires_confirmation, bool):
            requires_confirmation = True

        return CommandProposal(
            domain=str(domain).strip().lower(),
            operation=str(operation).strip(),
            arguments=arguments,
            explanation=str(explanation).strip(),
            requires_confirmation=requires_confirmation,
        )
